### ISSUE TITLE
哥们，你这个是干啥用的？

### ISSUE THREAD

**Issue by Light--** [Janspiry/face-mask-segmentation#1]
想问一下你把人脸分那么多patch下来为了做啥？另外，这个跟口罩有关系吗？能把人脸上的口罩分割下来吗？

**Comment by Janspiry** [comment]
感谢你的关注，这个mask指的是脸部掩膜，这些人脸patch是预处理，方便对特定部位进行加强学习

**Comment by Light--** [comment]
> 方便对特定部位进行加强学习

@Janspiry 
谢谢！但是怎么对特定部位加强学习呢？有repo或者相关内容可以分享吗？

**Comment by Janspiry** [comment]
我做的是GAN方面的工作，对特定部位约束可以提高局部效果，从而提升整体的真实性，链接https://blog.csdn.net/qq_40700490/article/details/108181644 里_Multi-discriminator:_
是类似的工作，repo暂时没有

**Comment by Light--** [comment]
> 我做的是GAN方面的工作，对特定部位约束可以提高局部效果，从而提升整体的真实性，链接https://blog.csdn.net/qq_40700490/article/details/108181644 里_Multi-discriminator:_

@Janspiry 
谢谢！我粗略概括一下你的思路哈：
1. 通过dlib等获取人脸关键点，根据每个部位中心点和patch大小获取groudtruth patch
2. 根据这些patch和原始图片，有监督地训练GAN，让GAN生成的图片和原始图片相近，尤其是在这些patch的部位要更相近。这就是你说的“对特定部位加强学习”
大概是这样么？

**Comment by Janspiry** [comment]
对的，但是这个GAN是借助监督机制使得图片更加真实，同时在这些patch的部位更加真实，和原始图片相近不是目的。
